// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMFaX_aoB7rbI9sid7Sn_B_nnPHmKl-44',
    appId: '1:1042207002105:web:4ba48ea09c4d4dcdb28128',
    messagingSenderId: '1042207002105',
    projectId: 'musicplayer-441e7',
    authDomain: 'musicplayer-441e7.firebaseapp.com',
    storageBucket: 'musicplayer-441e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMUcz25R7v4yvpnX4bj0FbU4ofSSLgqRk',
    appId: '1:1042207002105:android:0101ee1295cb34aeb28128',
    messagingSenderId: '1042207002105',
    projectId: 'musicplayer-441e7',
    storageBucket: 'musicplayer-441e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApm5JTR8H0EArqagdA8dorKfIechms87k',
    appId: '1:1042207002105:ios:d525cd600ae6ec62b28128',
    messagingSenderId: '1042207002105',
    projectId: 'musicplayer-441e7',
    storageBucket: 'musicplayer-441e7.appspot.com',
    iosBundleId: 'com.example.musicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApm5JTR8H0EArqagdA8dorKfIechms87k',
    appId: '1:1042207002105:ios:d525cd600ae6ec62b28128',
    messagingSenderId: '1042207002105',
    projectId: 'musicplayer-441e7',
    storageBucket: 'musicplayer-441e7.appspot.com',
    iosBundleId: 'com.example.musicPlayer',
  );
}
